### ISSUE TITLE
Complete design work of critical assets and sprites

### ISSUE THREAD

**Issue by ryanwarsaw** [ryanwarsaw/flapper#1]
This game is going to need a lot of different assets, here's a general list of what's needed in order to get a basic functioning game up and running: 

**Critical**
- [x] Character sprite, perhaps a pixel art version of Tucker the Toucan?
- [x] Background asset, we need some type of scenery going on in the background on repeat.
- [x] Obstacle asset, perhaps a totum pole, spooky street lamp, maybe a stack of pumpkins even.

**Non-Critical**
- [x] Maybe some fancy "sp0oky" themed buttons for the user interface.

**Comment by flukeout** [comment]
I made this for some mozilla project a while back...

![image](https://user-images.githubusercontent.com/25212/31160745-9bdcf88e-a887-11e7-99ac-690ead2c1905.png)

Wonder if that's an aesthetic we can go with here. I'll see if I have any other stuff I made already that might be suitable.

**Comment by flukeout** [comment]
Oh I just noticed you are going for a spooky theme. Maybe we can put a costume on tucker.

**Comment by ryanwarsaw** [comment]
I wanted to look into seeing if a pixel art version was possible, I can really appreciate vector art but I think a lot of youth are going to find it less challenging to work on pixels than vectors. 

I think a costume is a great idea, I want to see how aerodynamic tucker appears in-game, I noticed that flappy is a very narrow thin bird, where as tucker is a very proud and round toucan so I don't know if that'll effect how the game play appears to the user.

**Comment by flukeout** [comment]
Good call on pixel art being more accessible. Do you have a size / resolution in mind? I'll see if I have any original vector Tucker art to work from.

**Comment by flukeout** [comment]
![tucker](https://user-images.githubusercontent.com/25212/31199406-180b94ea-a90c-11e7-814a-3bfc5cedbb9a.png)

Found a fairly large .png image

**Comment by ryanwarsaw** [comment]
@flukeout Not sure, I'd like to see what an 8-bit style might look like, maybe a 10x10 grid.

Edit: That PNG should work well, I've got one as well but the colors are much more washed out, this one looks like a better solution.

**Comment by flukeout** [comment]
I'll see if I get some time to take a crack at it later today. 10 x 10 seems small though - will check.

**Comment by ryanwarsaw** [comment]
![tucker-pixelized](https://user-images.githubusercontent.com/6530909/31204720-c70686d2-a932-11e7-80ba-cc6ceee96c38.png)

@flukeout Thoughts? I did a complete transition from the original image, then made a few edits that I thought made the image look a bit more easy on the eyes.

Edit: I used an 8x8 grid, and once it's completed I'll write an SVG to split all the parts up so they can be animated, etc.

**Comment by ryanwarsaw** [comment]
### Tucker Pixelized
![tucker-pixelized](https://user-images.githubusercontent.com/6530909/31205035-80856b54-a934-11e7-8128-f90d1009ff27.png)

### Tucker Pixelized (Revised)
![tucker-pixelized-revised](https://user-images.githubusercontent.com/6530909/31205045-90ede14c-a934-11e7-9455-e53de422ea77.png)

The first image is an exact copy of what an 8x8 grid pixelation of the Tucker image would look like, and the revised version contains some adjustments for visible preference. Need to figure out what one we like better, and go with that one.

**Comment by flukeout** [comment]
I like the tail of the bottom one more, but the chest/torso of the top one.

**Comment by ryanwarsaw** [comment]
@flukeout I can make those changes, what are your thoughts about the wing animation? I want to divide this up into SVG sections, I'll split the top/bottom beak, the face/eyes and the two different colors of blue for the body, but am not sure where to cut the wing.

**Comment by flukeout** [comment]
Why do you want to make it into SVGs? I'd just create two bitmap images and use them them as background-images on some divs.

```
<div class='tucker-body'>
  <div class='tucker-wing'></div>
</div>
```

**Comment by ryanwarsaw** [comment]
@flukeout Tucker would be a single SVG, but I'd group the different components and that way you could control them all independently through the CSS. For example you could use a CSS fill to change the birds eye to a different color very easily, etc.

I thought it gave a bit more depth to potential modifications.

**Comment by flukeout** [comment]
That sounds like a great idea! I haven't messed around much with that approach. I'd still recommend breaking out the wing into a separate (and also CSS-able) sprite. The flap animation will be a lot better that way.

**Comment by ryanwarsaw** [comment]
@flukeout That's why I'm trying to figure out what the wing actually is, since technically it's all one giant body but I could do that once thats all figured out.

**Comment by flukeout** [comment]
This is what I'd figure...

<img width="495" alt="image" src="https://user-images.githubusercontent.com/25212/31206793-efe19604-a92e-11e7-9ef2-bdb0f1d99a1f.png">

If you cut that out, then you can fill in the missing part of tucker for the body sprite. I guess one drawback of going the SVG route is that then you can't really edit the pixel-art as easily during the session.

**Comment by ryanwarsaw** [comment]
I wonder if I could do both...

**Comment by ryanwarsaw** [comment]
![tucker-pixelized-revised-2](https://user-images.githubusercontent.com/6530909/31207742-b70d89a2-a945-11e7-99d8-41c7fcac31e8.png)

This is the revision with the changes you suggested, so changed the tail and left everything else the same. I did carry over the image alignments I did with the grid from the chest/torso version.

**Comment by ryanwarsaw** [comment]
Character has been completed, I uploaded all the source files for the whole thing into the assets/character folder. Moving on to the UI, and finally the background.

**Comment by ryanwarsaw** [comment]
This has been completed, everything has been uploaded to the `/assets` folder.
