### ISSUE TITLE
Identify and plan out all of the different in-game animations

### ISSUE THREAD

**Issue by ryanwarsaw** [ryanwarsaw/flapper#2]
It'd probably be pretty helpful to do this before an issue is ran into, this might require some work on the assets side, but I expect most of it can be done with CSS animations depending on how assets end up getting done (Not sure yet).

**Comment by flukeout** [comment]
For the tucker sprite, we could either do...

* A sort of two frame animation
  * Wings down, right after a flap, hold this for like .25 seconds
  * Wings up, all other times while free-falling after a flap
  * This would be easier I think.
    * We could add a third frame for when tucker hits something and starts falling
* A flap animation
  * We could try some little CSS animation where we divide tucker into two pieces, the body and the wing. When the player flaps, we trigger a CSS animation that moves the wings.
  * This could be more fun, as people could tweak the animation more easily

Other potential animations

* Maybe a little "bump" animation / effect when tucker runs into something
* Any kind of transitions needed between the different game states, assuming there are some?
  * Intro screen, game screen, game over screen?

The rest of the animations would just be a result of the level moving, so I don't think they need too much consideration.

**Comment by ryanwarsaw** [comment]
I'll make sure that the tucker asset gets pretty intricate with the SVG sections so either one of those options can be used, specifically define the wing separately from the body so that flap animation can be done.

**Comment by ryanwarsaw** [comment]
Need to figure out: 

- [ ] Main/Intro screen animation
- [ ] Game Over screen animation
- [ ] Tucker went splat! animation

**Comment by ryanwarsaw** [comment]
Done.
